\LoadClass[11pt,a4paper,sans]{moderncv}
% a4, a5, b5, legalpaper, executivepaper, landscape

% moderncv themes
\moderncvstyle{banking} % style options are 'casual' (default), 'classic', 'oldstyle' and 'banking'
\moderncvcolor{grey}% color options 'blue' (default), 'orange', 'green', 'red', 'purple', 'grey' and 'black'


% personal data
\name{Shubham}{Sharma}
%\title{Computer title} % optional, remove / comment the line if not wanted
\address{V-93/B, Sector-A}{Bhagwati Vihar, Uttam Nagar}{New Delhi(59), IN}% optional,
\phone[mobile]{+91~88260~54070} % optional, remove / comment the line if not wanted
\email{mr.shubhshar@gmail.com} % optional, remove / comment the line if not wanted
%\homepage{ajnorton.com} % optional, remove / comment the line if not wanted
\social[github][github.com/mr-shubhshar]{mr-shubhshar}
\social[twitter][twitter.com/mr_shubhshar]{mr\_shubhshar}




%\renewcommand{\familydefault}{\sfdefault} % to set the default font; use '\sfdefault' for the default sans serif font, '\rmdefault' for the default roman one, or any tex font name
%\nopagenumbers{} % uncomment to suppress automatic page numbering for CVs longer than one page


% character encoding for icons(or other complicated UTF characters) that LaTeX cannot decipher as of now
\RequirePackage[utf8]{inputenc}




\RequirePackage{geometry} % changes margins across the page
\geometry{
left=15mm,
right=15mm,
top=5mm,
bottom=5mm,
}
