\LoadClass[11pt,a4paper,sans]{moderncv}% possible options include font size ('10pt', '11pt' and '12pt'), paper size ('a4paper', 'letterpaper', 'a5paper', 'legalpaper', 'executivepaper' and 'landscape') and font family ('sans' and 'roman')


% moderncv themes
\moderncvstyle{banking}                            % style options are 'casual' (default), 'classic', 'oldstyle' and 'banking'
\moderncvcolor{grey}                                % color options 'blue' (default), 'orange', 'green', 'red', 'purple', 'grey' and 'black'
%\renewcommand{\familydefault}{\sfdefault}         % to set the default font; use '\sfdefault' for the default sans serif font, '\rmdefault' for the default roman one, or any tex font name
%\nopagenumbers{}                                  % uncomment to suppress automatic page numbering for CVs longer than one page


% character encoding
\RequirePackage[utf8]{inputenc}
\RequirePackage{geometry} % changes margins across the page
 \geometry{
 left=15mm,
 right=15mm,
 top=15mm,
 bottom=5mm,
}
\RequirePackage{amssymb}
\RequirePackage{fontawesome}
\RequirePackage{datetime}

\newcommand{\college}{Chitkara University}

% personal data
\name{Shubham}{Sharma}
%\title{Resumé title}                               % optional, remove / comment the line if not wanted

\address{V-93/B, Sector-A, Bhagwati Vihar}{Uttam Nagar, New Delhi 110059}{IN}% optional, remove / comment the line if not wanted; the "postcode city" and and "country" arguments can be omitted or provided empty
\phone[mobile]{+91~88260~54070 | +91~83685~46443}                   % optional, remove / comment the line if not wanted
\email{mr.shubhshar@gmail.com}                               % optional, remove / comment the line if not wanted
%\homepage{ajnorton.com}                          optional, remove / comment the line if not wanted
\social[github][github.com/mr-shubshar]{mr-shubhshar}
\social[twitter][twitter.com/mr\_shubhshar]{mr\_shubhshar}
